### ISSUE TITLE
Operator nightly is broken

### ISSUE THREAD

**Issue by vmuzikar** [keycloak-rel/keycloak-rel#23]
```
Could not find the selected project in the reactor: operator/app
```
https://github.com/keycloak-rel/keycloak-rel/runs/7442286567?check_suite_focus=true

**Comment by ahus1** [comment]
The latest changes built a new operator image, but failed to update the nightly branch of the kubernetes-k8s-resources repository: https://github.com/keycloak/keycloak-k8s-resources/tree/nightly/kubernetes

The resources there are still a month old. As they don't contain the latest changes when the operator changed from "deployment" to "statefulset", the current nightly operator image can't be installed with the resources provided in that repository branch. 

Even though the latest action is now green, the changes didn't end up there: https://github.com/keycloak-rel/keycloak-rel/actions/runs/2718813993
