### ISSUE TITLE
When the nightly build fails, the previous nightly build is also gone

### ISSUE THREAD

**Issue by ahus1** [keycloak-rel/keycloak-rel#47]
When starting a nightly build, it will first delete the existing nightly build. 

https://github.com/keycloak-rel/keycloak-rel/blob/7b705b0dc1e0c5a81de36812cf1118d78e4861c4/.github/workflows/x-create-gh-releases.yml#L40-L42

This leads to a situation that there is no nightly build when the nightly build will fail later. Even the previous one is then unavailable (like today).

This makes it difficult consume the nightly build for people who want to try it out, and for processed you want to test the latest nightly build for example in keycloak-benchmark. 

So I wonder: could this be changed? 

Pinging @jonkoops as you've been involved previously when this has been set up. Thanks!

**Comment by ahus1** [comment]
@kami619 - you might want to watch this issue as it affects the current setup of Minikube in keycloak-benchmark.

**Comment by jonkoops** [comment]
Yeah this is a problematic thing, perhaps we can create a draft release for the new nightly and then remove the old one and rename it?

**Comment by stianst** [comment]
Related to this is #50, which is resulting in a GH notification every time we do a nightly release.

**Comment by stianst** [comment]
Also related to this is the fact that releases are not "atomic". If a nightly release fails in the middle there may be some artefacts that  are updated, while others are not. That would improve if we don't publish things until the very end, which is a bit tricky with Maven, but something I would like as this is also problematic during a regular release if there is a failure part through. For example during 19.0.2 I ran into https://github.com/keycloak/keycloak-ui/issues/3323, which was a pain to recover from.

**Comment by stianst** [comment]
I can't think of a better option than using a "scratch" GH release during nightly releases, but not sure if we should rather just make sure nightly releases are stable as a priority?

**Comment by ahus1** [comment]
@stianst - removing the GH release during nightly releases might still be thing to do as it gives it a proper timestamp which make it turn up in the releases view in the right place. 

To still have a nightly release available even when the build fails, it might be possible to reorder things: 

Old behavior:
* delete old release and create a draft at the beginning
* each build step builds its artifacts and adds them to the draft release
* finally publishing the release

Suggestion for a new behavior: 
* each build step builds its artifacts and uploads them to the workflow run
* at the end, all artifacts are downloaded, the previous release is deleted, a new draft release created, artifacts are uploaded to the release, release is published (Note: the latest version of the download artifact GitHub action allows to download all artifacts at once - I never used that approach, just read the docs: https://github.com/actions/download-artifact)

The new behavior could reduce (a) the time gap while the nightly is running and (b) reduce the possibility that there is no nightly release due to a failed build.

**Comment by stianst** [comment]
@ahus1 for nightly releases using workflow artifacts would make perfect sense, but it would be problematic for regular releases if they fail midway through the release as we don't currently have a good way to fix/retry the release.

One problem I've had a few times now doing a release is one step has failed. If it's an issue in the code/release-branch then I can fix it there, and retry the failed steps in the workflow. However, if fixing the problem requires updating the workflow itself then I can't do that, and need to do another job, which requires disabling the non-repeatable steps like publishing to NPM or Maven, which then requires those artifacts to be available.

**Comment by stianst** [comment]
There's a pretty simple solution to this actually. We'll just leave the release if it's already created and instead overwrite files when uploading with '--clobber'.

That'll also help for https://github.com/keycloak-rel/keycloak-rel/issues/50 so we won't get notifications every night.
