### ISSUE TITLE
Trusted actions

### ISSUE THREAD

**Issue by stianst** [keycloak-rel/keycloak-rel#7]
We should probably be able to trust some actions, like those coming from GitHub themselves, and pin those to a specific major version rather than a SHA commit.

Some actions we should be able to trust include:

* actions/checkout
* docker/setup-qemu-action
* docker/setup-buildx-action
* docker/metadata-action
* docker/login-action

**Comment by andreaTP** [comment]
To add context, this will increase the security in the pipelines since we will automatically benefit from security patches done upstream without the need to actively bump versions or change SHAs.
