### ISSUE TITLE
Both main branch and upstream/XX.0 branches use the same 999-SNAPSHOT Version

### ISSUE THREAD

**Issue by rh-iatanaso** [keycloak-rel/keycloak-rel#84]
We have observed that both the main branch and upstream/21.0 branches use 999-SNAPSHOT for versioning.
While we understand that those are not published. This can make developing under 21.0 and main at the same time error-prone because the local snapshot might not always be updated. The protection against issue that arise from this behavior would be to force maven to validate the snapshots every time, which will reduce the performance of local builds

**Comment by stianst** [comment]
Incorporated as part of https://github.com/keycloak-rel/keycloak-rel/issues/104
